version: 1.0.{build}
build:
  verbosity: minimal
artifacts:
  - path: main.pdf
    name: Paper
deploy:
  - provider: GitHub
    description: The newly compiled paper in PDF format.
    auth_token:
      secure: AxKyd9x91aD6ZpLtvmw8iQvR1LkvduvZUcJbU2zqwbWXBBr2SI/cr4jod8SIQHmB
    repository: cgsdfc/ICONIP2019
    artifact: Paper
    draft: false
    force_update: true