version: 1.0.{build}
image: Visual Studio 2017
install:
  - ps: choco install -y miktex
  - cmd: refreshenv

build_script:
  - cmd: latexmk .\main.tex -pdf

artifacts:
  - path: main.pdf
    name: Paper
deploy:
  - provider: GitHub
    description: The newly compiled paper in PDF format.
    auth_token:
      secure: AxKyd9x91aD6ZpLtvmw8iQvR1LkvduvZUcJbU2zqwbWXBBr2SI/cr4jod8SIQHmB
    repository: cgsdfc/ICONIP2019
    artifact: Paper
    draft: false
    force_update: true
